# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cme_open_interest_aggregation.proto, funding_rate_aggregation.proto, hyperliquid_liquidation_aggregation.proto, liquidation_aggregation.proto, open_interest_aggregation.proto, option_open_interest_aggregation.proto, timestamp/timestamp.proto, trade.proto, trade_aggregation.proto, trade_side_agnostic_aggregation.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
)

import betterproto


@dataclass(eq=False, repr=False)
class Timestamp(betterproto.Message):
    """
    Timestamp is a point in time represented as seconds and fractions of seconds at nanosecond resolution in UTC since Unix epoch.
    """

    seconds: int = betterproto.fixed32_field(1)
    nanoseconds: int = betterproto.fixed32_field(2)


@dataclass(eq=False, repr=False)
class CmeOpenInterestAggregation(betterproto.Message):
    open: float = betterproto.double_field(1)
    high: float = betterproto.double_field(2)
    low: float = betterproto.double_field(3)
    close: float = betterproto.double_field(4)
    value_open: float = betterproto.double_field(5)
    value_high: float = betterproto.double_field(6)
    value_low: float = betterproto.double_field(7)
    value_close: float = betterproto.double_field(8)
    price_open: float = betterproto.double_field(9)
    price_high: float = betterproto.double_field(10)
    price_low: float = betterproto.double_field(11)
    price_close: float = betterproto.double_field(12)
    timestamp: "Timestamp" = betterproto.message_field(13)


@dataclass(eq=False, repr=False)
class FundingRateAggregation(betterproto.Message):
    rate_open: float = betterproto.double_field(1)
    rate_high: float = betterproto.double_field(2)
    rate_low: float = betterproto.double_field(3)
    rate_close: float = betterproto.double_field(4)
    predicted_open: float = betterproto.double_field(5)
    predicted_high: float = betterproto.double_field(6)
    predicted_low: float = betterproto.double_field(7)
    predicted_close: float = betterproto.double_field(8)
    timestamp: "Timestamp" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class HyperliquidLiquidationAggregation(betterproto.Message):
    timestamp: "Timestamp" = betterproto.message_field(1)
    coin: str = betterproto.string_field(2)
    levels: List[float] = betterproto.double_field(5)


@dataclass(eq=False, repr=False)
class LiquidationAggregation(betterproto.Message):
    liquidations: float = betterproto.double_field(1)
    timestamp: "Timestamp" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class OpenInterestAggregation(betterproto.Message):
    open: float = betterproto.double_field(1)
    high: float = betterproto.double_field(2)
    low: float = betterproto.double_field(3)
    close: float = betterproto.double_field(4)
    timestamp: "Timestamp" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class OptionOpenInterestAggregation(betterproto.Message):
    underlying_price_close: float = betterproto.double_field(1)
    oi_close: float = betterproto.double_field(2)
    timestamp: "Timestamp" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TradeAggregation(betterproto.Message):
    """Represents aggregated trade data for a specific time period"""

    open: float = betterproto.double_field(1)
    """Opening price for the aggregation period"""

    high: float = betterproto.double_field(2)
    """Highest price reached during the aggregation period"""

    low: float = betterproto.double_field(3)
    """Lowest price reached during the aggregation period"""

    close: float = betterproto.double_field(4)
    """Closing price for the aggregation period"""

    volume: float = betterproto.double_field(5)
    """Total trading volume during the aggregation period"""

    timestamp: "Timestamp" = betterproto.message_field(6)
    """Timestamp representing the start of the aggregation period"""

    first_timestamp: "Timestamp" = betterproto.message_field(7)
    """Timestamp of the first trade in the aggregation period"""

    last_timestamp: "Timestamp" = betterproto.message_field(8)
    """Timestamp of the last trade in the aggregation period"""


@dataclass(eq=False, repr=False)
class Trade(betterproto.Message):
    """Represents a single trade transaction"""

    id: str = betterproto.string_field(1)
    """Unique exchange-native identifier of the trade"""

    price: float = betterproto.double_field(2)
    """Price at which the trade was executed"""

    amount: float = betterproto.double_field(3)
    """Quantity of the asset traded"""

    timestamp: "Timestamp" = betterproto.message_field(4)
    """Timestamp when the trade occurred"""


@dataclass(eq=False, repr=False)
class TradeSideAgnosticAggregation(betterproto.Message):
    """
    Represents aggregated trade data for a specific time period, but without Side
     grouping
    """

    open: float = betterproto.double_field(1)
    """Opening price for the aggregation period"""

    high: float = betterproto.double_field(2)
    """Highest price reached during the aggregation period"""

    low: float = betterproto.double_field(3)
    """Lowest price reached during the aggregation period"""

    close: float = betterproto.double_field(4)
    """Closing price for the aggregation period"""

    volume: float = betterproto.double_field(5)
    """Total trading volume during the aggregation period"""

    timestamp: "Timestamp" = betterproto.message_field(6)
    """Timestamp representing the start of the aggregation period"""

    first_timestamp: "Timestamp" = betterproto.message_field(7)
    """Timestamp of the first trade in the aggregation period"""

    last_timestamp: "Timestamp" = betterproto.message_field(8)
    """Timestamp of the last trade in the aggregation period"""
